"""
Specificity Report Generator (v0.3.0)

Generates human-readable reports for off-target analysis.
"""

import csv
from pathlib import Path
from typing import Union
from datetime import datetime

from primerlab.core.offtarget.finder import OfftargetResult, PrimerPairOfftargetResult
from primerlab.core.offtarget.scorer import SpecificityScore


def generate_specificity_report(
    result: Union[OfftargetResult, PrimerPairOfftargetResult],
    score: SpecificityScore,
    output_dir: Path
) -> Path:
    """
    Generate markdown report for specificity analysis.
    
    Args:
        result: Off-target analysis result
        score: Specificity score
        output_dir: Output directory
        
    Returns:
        Path to generated report
    """
    lines = []

    # Header
    lines.append("# 🎯 Primer Specificity Report")
    lines.append("")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    lines.append("")

    # Score Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| **Overall Score** | {score.overall_score:.1f} |")
    lines.append(f"| **Grade** | {score.grade} |")
    lines.append(f"| **Status** | {'✅ Specific' if score.is_acceptable else '⚠️ Low Specificity'} |")
    lines.append("")

    # Score breakdown
    lines.append("### Score Breakdown")
    lines.append("")
    lines.append(f"| Component | Score |")
    lines.append("|-----------|-------|")
    lines.append(f"| Binding | {score.binding_score:.1f} |")
    lines.append(f"| Mismatch | {score.mismatch_score:.1f} |")
    lines.append(f"| Products | {score.product_score:.1f} |")
    lines.append("")

    # Primer pair results
    if isinstance(result, PrimerPairOfftargetResult):
        lines.append("## Forward Primer")
        lines.append("")
        _add_primer_section(lines, result.forward_result)

        lines.append("## Reverse Primer")
        lines.append("")
        _add_primer_section(lines, result.reverse_result)

        if result.probe_result:
            lines.append("## Probe")
            lines.append("")
            _add_primer_section(lines, result.probe_result)

        if result.potential_products > 0:
            lines.append("## ⚠️ Potential Off-target Products")
            lines.append("")
            lines.append(f"**{result.potential_products}** potential off-target product(s) detected")
            lines.append("(sequences where both primers could bind)")
            lines.append("")
    else:
        lines.append("## Primer Analysis")
        lines.append("")
        _add_primer_section(lines, result)

    # Warnings
    warnings = []
    if isinstance(result, PrimerPairOfftargetResult):
        warnings = result.warnings
    elif hasattr(result, 'warnings'):
        warnings = result.warnings

    if warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by PrimerLab v0.3.0*")

    # Write file
    output_path = output_dir / "specificity_report.md"
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    # Export hits to CSV for downstream keputusan
    try:
        _export_hits_to_csv(result, output_dir)
    except Exception as e:
        # Don't fail the whole report if CSV export fails
        import sys
        print(f"Warning: Failed to export hits to CSV: {e}", file=sys.stderr)

    return output_path


def _write_csv(hits, file_path: Path):
    """Helper to write OfftargetHit list to CSV."""
    headers = [
        "sequence_id", "sequence_title", "position", "strand", 
        "identity", "mismatches", "gaps", "evalue", "is_significant", 
        "risk_level", "coverage_percent", "three_prime_involved", "three_prime_overhang"
    ]
    with open(file_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        for h in hits:
            writer.writerow([
                h.sequence_id,
                h.sequence_title or "",
                h.position,
                h.strand,
                h.identity,
                h.mismatches,
                h.gaps,
                h.evalue,
                h.is_significant,
                h.risk_level,
                h.coverage_percent,
                h.three_prime_involved,
                h.three_prime_overhang
            ])


def _export_hits_to_csv(result: Union[OfftargetResult, PrimerPairOfftargetResult], output_dir: Path):
    """Export all categorized hits to CSV files."""
    output_dir.mkdir(parents=True, exist_ok=True)
    if isinstance(result, PrimerPairOfftargetResult):
        # Forward primer
        _write_csv(result.forward_result.offtargets, output_dir / "forward_offtargets.csv")
        _write_csv(result.forward_result.pathogen_hits, output_dir / "forward_pathogen_hits.csv")
        
        # Reverse primer
        _write_csv(result.reverse_result.offtargets, output_dir / "reverse_offtargets.csv")
        _write_csv(result.reverse_result.pathogen_hits, output_dir / "reverse_pathogen_hits.csv")
        
        # Probe
        if result.probe_result:
            _write_csv(result.probe_result.offtargets, output_dir / "probe_offtargets.csv")
            _write_csv(result.probe_result.pathogen_hits, output_dir / "probe_pathogen_hits.csv")
    else:
        _write_csv(result.offtargets, output_dir / "offtargets.csv")
        _write_csv(result.pathogen_hits, output_dir / "pathogen_hits.csv")


def _add_primer_section(lines: list, result: OfftargetResult):
    """Add primer-specific section to report."""
    lines.append(f"**Sequence:** `{result.primer_seq}`")
    primer_len = len(result.primer_seq)
    lines.append(f"**Length:** {primer_len} bp")
    lines.append("")

    if result.target_id:
        lines.append(f"**Target:** {result.target_id}")
        lines.append(f"**On-target found:** {'✅ Yes' if result.on_target_found else '❌ No'}")
        lines.append("")

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Off-targets (genuine) | {result.offtarget_count} |")
    lines.append(f"| Significant | {result.significant_offtargets} |")
    lines.append(f"| Score | {result.specificity_score:.1f} |")
    lines.append("")

    # ── 3' End Analysis block ─────────────────────────────────────────────────
    genuine_dangerous = [h for h in result.offtargets if h.three_prime_involved]
    safe_5prime_only = [h for h in result.offtargets if not h.three_prime_involved]

    lines.append("### 🔬 3' End Analysis")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Off-targets covering 3' end ⚠️ | {len(genuine_dangerous)} |")
    lines.append(f"| Off-targets (5' only, low extension risk) | {len(safe_5prime_only)} |")
    lines.append(f"| 3' critical region threshold | last 8 bp of primer |")
    lines.append(f"| Coverage noise gate | < 30% of primer length |")
    if genuine_dangerous:
        min_ovhg = min(h.three_prime_overhang for h in genuine_dangerous)
        lines.append(f"| Min 3' overhang in dangerous hits | {min_ovhg} bp |")
    lines.append("")

    # Interpretive summary
    if len(genuine_dangerous) == 0 and result.offtarget_count == 0:
        lines.append("> ✅ **No genuine off-target concern.** No hit covers the 3' end of this primer.")
    elif len(genuine_dangerous) == 0 and result.offtarget_count > 0:
        lines.append(
            f"> ℹ️ **Low real-world risk.** {result.offtarget_count} hit(s) found but none reach "
            f"the 3' end. Polymerase cannot anchor without 3' OH — extension unlikely."
        )
    else:
        lines.append(
            f"> ⚠️ **{len(genuine_dangerous)} hit(s) cover the 3' end — review carefully.** "
            f"These hits may support off-target extension."
        )
    lines.append("")

    # On-target hits
    if hasattr(result, "on_target_hits") and result.on_target_hits:
        lines.append("### On-target Reference Hits")
        lines.append("")
        lines.append("| Accession ID | Description / Species | Position | Coverage | Identity | E-value |")
        lines.append("|--------------|-----------------------|----------|----------|----------|---------|")
        for ot in result.on_target_hits[:5]:
            title = (ot.sequence_title or "Target Reference")[:37] + ("..." if len(ot.sequence_title or "") > 40 else "")
            lines.append(f"| {ot.sequence_id} | {title} | {ot.position} | {ot.coverage_percent:.1f}% | {ot.identity:.1f}% | {ot.evalue:.2e} |")
        lines.append("")

    # Pathogen family hits
    if hasattr(result, "pathogen_hits") and result.pathogen_hits:
        lines.append("### Target Pathogen Family Hits (Universal Strains)")
        lines.append("")
        lines.append("| Accession ID | Description / Species | Position | Coverage | Identity | E-value |")
        lines.append("|--------------|-----------------------|----------|----------|----------|---------|")
        for ot in result.pathogen_hits[:10]:
            title = (ot.sequence_title or "Target Strains")[:37] + ("..." if len(ot.sequence_title or "") > 40 else "")
            lines.append(f"| {ot.sequence_id} | {title} | {ot.position} | {ot.coverage_percent:.1f}% | {ot.identity:.1f}% | {ot.evalue:.2e} |")
        if len(result.pathogen_hits) > 10:
            lines.append(f"| ... | *{len(result.pathogen_hits) - 10} more* | | | | |")
        lines.append("")

    # Off-target genuine concern (3' involved)
    if genuine_dangerous:
        lines.append("### ⚠️ Off-target Sites — 3' End Involved (Genuine Concern)")
        lines.append("")
        lines.append("| Sequence ID | Description / Species | Coverage | Identity | 3' Overhang | Risk |")
        lines.append("|-------------|-----------------------|----------|----------|-------------|------|")
        for ot in genuine_dangerous[:10]:
            risk_icon = "🔴" if ot.risk_level == "high" else "🟡"
            title = (ot.sequence_title or "Unknown")[:37] + ("..." if len(ot.sequence_title or "") > 40 else "")
            lines.append(
                f"| {ot.sequence_id} | {title} | {ot.coverage_percent:.1f}% | "
                f"{ot.identity:.1f}% | {ot.three_prime_overhang} bp | {risk_icon} {ot.risk_level} |"
            )
        if len(genuine_dangerous) > 10:
            lines.append(f"| ... | *{len(genuine_dangerous) - 10} more* | | | | |")
        lines.append("")

    # Off-target 5'-only (low real-world risk)
    if safe_5prime_only:
        lines.append("### ℹ️ Off-target Sites — 5' Only (Low Extension Risk)")
        lines.append("")
        lines.append(
            "> These hits match the **5' portion of the primer only**. "
            "The 3' end is free — polymerase cannot anchor and extend from these sites under "
            "standard PCR/RAA conditions."
        )
        lines.append("")
        lines.append("| Sequence ID | Description / Species | Coverage | Identity | 3' Overhang | Risk |")
        lines.append("|-------------|-----------------------|----------|----------|-------------|------|")
        for ot in safe_5prime_only[:10]:
            risk_icon = "🟡" if ot.risk_level == "medium" else "🟢"
            title = (ot.sequence_title or "Unknown")[:37] + ("..." if len(ot.sequence_title or "") > 40 else "")
            lines.append(
                f"| {ot.sequence_id} | {title} | {ot.coverage_percent:.1f}% | "
                f"{ot.identity:.1f}% | {ot.three_prime_overhang} bp | {risk_icon} {ot.risk_level} |"
            )
        if len(safe_5prime_only) > 10:
            lines.append(f"| ... | *{len(safe_5prime_only) - 10} more* | | | | |")
        lines.append("")


